"""Offline gazetteer of Italian municipalities (de-Milanization, plan A).

The repair heuristics and the geocoder's coordinate sanity check used to lean
on hand-enumerated lists (~70 city names, 26 bounding boxes) that silently
degraded outside Milan's orbit. This module replaces those allow-lists with the
authoritative set: all ~7,900 comuni from ISTAT, with GeoNames-derived
centroids, bundled as a read-only SQLite (``app/data/comuni.sqlite``, ~800 KB,
regenerated by ``scripts/build_comuni_dataset.py`` — dev-only, never fetched at
runtime, so the Raspberry-Pi/offline guarantee holds).

Design rules, mirroring the rest of the codebase:

* **Fail-open, never a guess.** ``detect_city`` returns ``""`` when unsure —
  there is no Milan (or any) default. ``is_plausible_coordinate`` only ever
  accepts/rejects a candidate pin; an unknown or ambiguous city degrades to the
  Italy-bbox check, exactly what the old boxes' ``return True`` default did.
* **The user already told us the city.** Every active search profile encodes
  its city, so callers pass those in as the first detection layer
  (``profile_cities``): always correct for this user, near-zero cost. The
  bundled index is the safety net for imports and ad-hoc text from anywhere in
  Italy.
"""

import re
import sqlite3
import unicodedata
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

from .geo_filter import haversine_m

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "comuni.sqlite"

# Roughly Italy, incl. islands — same bounds the old geocoder check used.
ITALY_LAT = (35.0, 47.5)
ITALY_LNG = (6.5, 18.6)

# The plausibility radius is per-comune, derived from its postal-code count (a
# size proxy the GeoNames data gives for free): radius = BASE + SCALE·√CAPs,
# clamped. Calibration anchor: Milano (38 CAPs → ~12 km) must keep rejecting
# the historical "Via Tolmezzo geocoded to Cernusco sul Naviglio" pin (13 km
# out — the exact case the old hand-drawn box caught), while a village's 8 km
# floor still absorbs its frazioni.
RADIUS_BASE_M = 6_000.0
RADIUS_SCALE_M = 1_000.0
RADIUS_MIN_M = 8_000.0
RADIUS_MAX_M = 30_000.0

# Two comuni sharing a name (e.g. Castro BG / Castro LE): when their centroids
# sit within this radius the average is still meaningful, otherwise the name is
# ambiguous and the centroid lookup answers None (fail-open).
AMBIGUITY_RADIUS_M = 30_000.0

# Single very short comune names ("Re" VB, "Vo'" PD, "Ne" GE) collide with
# ordinary words far too often for free-text detection; multi-word names and
# names this long are safe.
MIN_SINGLE_TOKEN_LEN = 4


def _normalize_place(text: str) -> str:
    """Accent-insensitive, lowercase, hyphen->space, collapsed whitespace.

    Must mirror ``normalize()`` in ``scripts/build_comuni_dataset.py`` — the
    lookup keys in the bundled SQLite were written with that function.
    """
    text = unicodedata.normalize("NFKD", text or "")
    text = "".join(c for c in text if not unicodedata.combining(c))
    text = " ".join(text.lower().replace("-", " ").replace("'", "' ").split())
    return text.replace("' ", "'")


@dataclass(frozen=True)
class Comune:
    name: str
    province: str
    province_sigla: str
    region: str
    lat: float | None
    lng: float | None
    postal_count: int = 0

    @property
    def radius_m(self) -> float:
        """Plausibility radius scaled to the comune's size (√ of its CAPs)."""
        r = RADIUS_BASE_M + RADIUS_SCALE_M * (self.postal_count**0.5)
        return min(max(r, RADIUS_MIN_M), RADIUS_MAX_M)


class ComuneIndex:
    """In-memory lookup over the bundled dataset: name_norm -> [Comune]."""

    def __init__(self, by_name: dict[str, list[Comune]], max_words: int):
        self._by_name = by_name
        # longest name in the index, in words — bounds the n-gram scan
        self.max_words = max_words

    def lookup(self, name: str) -> list[Comune]:
        return self._by_name.get(_normalize_place(name), [])

    def __contains__(self, name: str) -> bool:
        return _normalize_place(name) in self._by_name


@lru_cache(maxsize=1)
def load_comuni() -> ComuneIndex:
    """Lazy, cached read of the bundled dataset.

    A missing/corrupt data file degrades to an empty index (every lookup
    misses, detection falls back to the profile-cities layer) rather than
    crashing a maintenance action — the callers were heuristics to begin with.
    """
    by_name: dict[str, list[Comune]] = {}
    max_words = 1
    try:
        con = sqlite3.connect(f"file:{DATA_PATH}?mode=ro", uri=True)
        try:
            rows = con.execute(
                "SELECT n.name_norm, c.name, c.province, c.province_sigla, c.region,"
                " c.lat, c.lng, c.postal_count"
                " FROM comune_names n JOIN comuni c ON c.id = n.comune_id"
            ).fetchall()
        finally:
            con.close()
    except sqlite3.Error:
        return ComuneIndex({}, 1)
    for name_norm, name, province, sigla, region, lat, lng, postal_count in rows:
        by_name.setdefault(name_norm, []).append(
            Comune(name, province, sigla, region, lat, lng, postal_count or 0)
        )
        max_words = max(max_words, len(name_norm.split()))
    return ComuneIndex(by_name, max_words)


_TOKEN_SPLIT = re.compile(r"[^\w']+")


def detect_city(text: str, profile_cities: tuple[str, ...] | list[str] = ()) -> str:
    """Best city mentioned in `text`, or "" — never a default.

    Layered on purpose (plan A.3): the caller's profile cities are checked
    first (word-boundary, in the given order — always right for this user),
    then the full comuni index via an n-gram scan preferring the longest match
    ("Sesto San Giovanni" must not come back as a hypothetical "Sesto"). The
    returned string is the surface form title-cased for profile matches, and
    the matched variant title-cased for index hits — NOT the official ISTAT
    name, because the scrapers store the everyday form ("Reggio Emilia") and a
    differently-spelled repair would block cross-portal merges (invariant 1).
    """
    if not text:
        return ""
    norm = _normalize_place(text.replace("_", " ").replace("/", " "))
    if not norm:
        return ""
    for city in profile_cities:
        pattern = _place_pattern(city)
        if pattern and pattern.search(norm):
            return city.strip()
    index = load_comuni()
    tokens = [t for t in _TOKEN_SPLIT.split(norm) if t]
    best = ""
    for size in range(min(index.max_words, len(tokens)), 0, -1):
        for start in range(0, len(tokens) - size + 1):
            gram = " ".join(tokens[start : start + size])
            if size == 1 and len(gram) < MIN_SINGLE_TOKEN_LEN:
                continue
            if index.lookup(gram):
                best = gram
                break
        if best:
            break
    return best.title() if best else ""


@lru_cache(maxsize=256)
def _place_pattern(place: str) -> re.Pattern | None:
    """Word-boundary pattern for a place name, in normalized space (the same
    matching discipline as filter_engine: "asta" ⊄ "Castanese")."""
    words = _normalize_place(place).split()
    if not words:
        return None
    body = r"\s+".join(re.escape(w) for w in words)
    return re.compile(rf"(?<!\w){body}(?!\w)")


def _centroid_and_radius(city: str) -> tuple[float, float, float] | None:
    """(lat, lng, radius_m) for the comune, or None when unknown or ambiguous.

    A name shared by two distant comuni (Castro BG vs Castro LE) answers None
    — a centroid that might be 800 km off is worse than no centroid — and so
    does a name whose homonyms are only partially located: proximity between
    them cannot be verified, so no guess.
    """
    matches = load_comuni().lookup(city)
    if not matches:
        return None
    located = [c for c in matches if c.lat is not None and c.lng is not None]
    if not located or len(located) < len(matches):
        return None
    lats = [c.lat for c in located if c.lat is not None]
    lngs = [c.lng for c in located if c.lng is not None]
    center = (sum(lats) / len(lats), sum(lngs) / len(lngs))
    for c in located:
        assert c.lat is not None and c.lng is not None
        if haversine_m(c.lat, c.lng, *center) > AMBIGUITY_RADIUS_M:
            return None
    return center[0], center[1], max(c.radius_m for c in located)


def city_centroid(city: str) -> tuple[float, float] | None:
    """(lat, lng) of the comune, or None when unknown or ambiguous."""
    found = _centroid_and_radius(city)
    return (found[0], found[1]) if found else None


def is_plausible_coordinate(lat: float | None, lng: float | None, city: str) -> bool:
    """Is (lat, lng) a believable pin for `city`?

    Inside the Italy bbox always required; when the comune has a known
    centroid, the pin must also sit within the comune's own size-scaled
    radius. Unknown or ambiguous city -> bbox check only, which is exactly
    what the old hand-drawn boxes' `return True` default did for the ~7,870
    comuni they never covered — so no regression, only 300× more coverage.
    """
    if lat is None or lng is None:
        return False
    if not (ITALY_LAT[0] <= lat <= ITALY_LAT[1] and ITALY_LNG[0] <= lng <= ITALY_LNG[1]):
        return False
    found = _centroid_and_radius(city) if city else None
    if found is None:
        return True
    c_lat, c_lng, radius = found
    return haversine_m(lat, lng, c_lat, c_lng) <= radius
