/** The application's type vocabulary.
 *
 *  Two halves, and the split is the point. Everything the **backend** describes
 *  is an alias onto `api.ts`, which is generated from the OpenAPI document
 *  (`python scripts/gen_api_types.py`) — so a field renamed in `schemas.py`
 *  fails the build here instead of becoming an `undefined` in the browser. This
 *  file used to be a 583-line hand-written twin of that document, and nothing
 *  made the two agree.
 *
 *  Everything the **browser** owns and the backend has never heard of — form
 *  state, the shapes the UI groups things into, the view mode — is declared
 *  below, by hand, because there is nothing to generate it from.
 *
 *  The names are ours, not the wire's: `Property`, not `PropertyOut`. One line
 *  of aliasing keeps every call site reading like the product rather than like
 *  a Pydantic module.
 */
import type { components } from "./api";

type Schemas = components["schemas"];

// --- What the backend describes ---

/** Tail of the backend's own app.log, for the in-app log viewer. */
export type LogTail = Schemas["LogTailOut"];
/** Single portal ad associated with a deduplicated Property. */
export type Listing = Schemas["ListingOut"];
/** Record of a historical price variation on a Property. */
export type PricePoint = Schemas["PriceHistoryOut"];
/** A user-defined free-form category ("senza ascensore", "con giardino", ...).
 *  `count` (usage across properties) is only meaningful on the list returned by
 *  GET /api/tags, not on the copies nested in Property.tags. */
export type Tag = Schemas["TagOut"];
/** Deduplicated physical property merging identical ads across portals/agencies. */
export type Property = Schemas["PropertyOut"];
/** One routed leg from a property to a saved place. Raw metres and seconds: the
 *  formatting ("12 min", "3.2 km") is this layer's job. */
export type Commute = Schemas["CommuteOut"];
export type CommuteMode = Commute["mode"];
/** A place the user commutes to, as stored in the settings. Either an address
 *  (geocoded once, then remembered) or an explicit pin. */
export type CommutePoint = Schemas["CommutePointOut"];
/** What the optional model read in one listing's text. Deliberately not part of
 *  `Property`: it exists only for the properties the user asked about, and the
 *  detail view fetches it on its own. */
export type ListingAudit = Schemas["ListingAuditOut"];
/** A monitored search that found a property, shown on its card. */
export type ProfileRef = Schemas["ProfileRef"];
/** Extracted or computed criteria from a search profile's URL. */
export type SearchProfileParams = Schemas["SearchBuilderParamsOut"];
/** Monitored search profile running scheduled or manual portal scrapes. */
export type SearchProfile = Schemas["SearchProfileOut"];
/** What a search has produced in the dashboard, and what deleting it would take
 *  with it. */
export type ProfileResults = Schemas["ProfileResultsOut"];
export type ProfileBulkResult = Schemas["ProfileBulkOut"];
/** User-configurable application preferences persisted in settings.json. */
export type Settings = Schemas["SettingsOut"];
/** Status and timing details of background scan execution, plus the live
 *  progress of the scan in flight. */
export type ScanStatus = Schemas["ScraperStatusOut"];
/** What the scan in flight is doing right now. `total_pages`/`total_listings`
 *  are null unless the portal declared them — a proportion may only be drawn
 *  against a real total. */
export type ScanProgress = Schemas["ScanProgressOut"];
/** One search's line in the scan journal. */
export type ScanJournalEntry = Schemas["ScanJournalEntryOut"];
/** One window of the filtered property set. `total` sizes the whole filtered
 *  set, not `items`. */
export type PropertyPage = Schemas["PropertyPage"];
/** Portal URLs generated by the native search builder. */
export type SearchBuilderUrls = Schemas["SearchBuilderUrlsOut"];
/** One search alternative the assistant understood ("bilocale in zona X o
 *  trilocale in zona Y" yields two of these). */
export type AssistantSearch = Schemas["AssistantSearch"];
/** What the natural-language assistant understood, before anything is saved. */
export type AssistantResult = Schemas["AssistantOut"];
/** Outcome of probing dashboard properties against the portals. `unknown` counts
 *  the ones the portal would not answer for (a block, a timeout): not gone. */
export type AvailabilityCheckSummary = Schemas["AvailabilityCheckSummaryOut"];
export type AvailabilityCheckProgress = Schemas["AvailabilityCheckProgressOut"];
export type AreaVelocity = Schemas["AreaVelocityOut"];
export type AgencyBehavior = Schemas["AgencyBehaviorOut"];
export type MarketVelocity = Schemas["MarketVelocityOut"];
export type ScraperHealthDay = Schemas["ScraperHealthDayOut"];
export type ScraperHealthPortal = Schemas["ScraperHealthPortalOut"];
export type ScraperHealthProfileStreak = Schemas["ScraperHealthProfileOut"];
export type ScraperHealth = Schemas["ScraperHealthOut"];
export type PricingTrendPoint = Schemas["PricingTrendPoint"];
export type PricingTrend = Schemas["PricingTrendOut"];
export type TrendArea = Schemas["TrendAreaOut"];
export type GeocodeProgress = Schemas["GeocodeProgressOut"];
export type GeocodeSummary = Schemas["GeocodeSummaryOut"];
export type CommuteProgress = Schemas["CommuteProgressOut"];
export type CommuteSummary = Schemas["CommuteSummaryOut"];
/** One copy of the database in the backups folder. `kind` decides what the row
 *  says: `daily` is one of the fourteen rotating copies, `pre-upgrade` is the
 *  state a version change left behind, `imported` came from another install. */
export type BackupFile = Schemas["BackupFileOut"];

/** The fields a settings form may send back. Deliberately the *input* model and
 *  not `Partial<Settings>`: the response carries the `*_set` booleans and the
 *  `*_available` flags, which are things the backend reports and nothing may
 *  post — and posting a masked secret back is how a stored key gets overwritten
 *  with three asterisks. */
export type SettingsPatch = Schemas["SettingsIn"];

// --- What only the browser has ---

/** A grouped/unified search containing one or more SearchProfiles (e.g.
 *  Immobiliare + Idealista). Assembled in the client from the flat list the API
 *  returns: the pairing is a presentation decision, and the backend stores each
 *  portal's search as its own profile. */
export interface GroupedSearchProfile {
  baseName: string;
  profiles: SearchProfile[];
  ids: number[];
  portals: string[];
  is_active: boolean;
  notify_channels: string;
  consecutive_failures: number;
  last_run_status: string;
  last_run_detail: string;
  excluded_keywords: string;
}

/** User-selected filter state for querying properties in the UI.
 *
 *  Strings throughout, including the numeric fields: this is what the inputs
 *  hold and what goes into the querystring, so an empty field is "" rather than
 *  a number that has to mean "unset". The backend's own parameters are typed on
 *  the query side of `api.ts`. */
export interface PropertyFilters {
  status: string;
  contract: "sale" | "rent";
  city: string;
  zone: string;
  q: string;                 // free-text search (title/zone/address/description)
  source: "" | "scan" | "email";  // "" = both origins
  profile_id: string;        // "" = no monitored-search overlay
  tag: string;                // "" = no tag filter; tag name, case-insensitive
  min_price: string;
  max_price: string;
  min_sqm: string;
  max_sqm: string;
  // "" = any floor; bands parsed server-side from the free-text floor label
  floor_band: "" | "ground" | "low" | "mid" | "high" | "top";
  rooms: string;
  // --- advanced filters (behind the "More filters" panel) ---
  portal: "" | "immobiliare" | "idealista";  // "" = any portal
  agency: string;                             // substring match on the agency
  deal: "" | "undervalued" | "fair_plus";     // "" = any deal score
  min_sqm_price: string;                       // €/sqm band (derived price÷sqm)
  max_sqm_price: string;
  merged_only: boolean;                        // only cards backed by >1 ad
  // --- geographic zone drawn on the map (radius or polygon, mutually exclusive) ---
  geo_mode: "" | "radius" | "polygon";         // "" = no geo filter
  center_lat: string;                          // radius mode: circle centre
  center_lng: string;
  radius_m: string;                            // radius in metres
  poly: string;                                // polygon mode: "lat,lng;lat,lng;…"
  only_price_drops: boolean;
  only_favorites: boolean;
  sort: string;
}

/** The subset of PropertyFilters the map's drawing tools own. */
export interface GeoFilter {
  geo_mode: "" | "radius" | "polygon";
  center_lat: string;
  center_lng: string;
  radius_m: string;
  poly: string;
}

/** Structured parameters used to synthesize portal search URLs.
 *
 *  The builder *form*, not the wire payload: every numeric field is the string
 *  its input holds, and `api.buildSearchUrls` converts them on the way out. */
export interface SearchBuilderParams {
  city: string;
  province: string;
  zone: string;
  contract: "sale" | "rent";
  min_price: string;
  max_price: string;
  min_rooms: string;
  max_rooms: string;
  min_sqm: string;
  balcony: boolean;
  garden: boolean;
  parking: boolean;
  elevator: boolean;
  exclude_auctions: boolean;
  pool: boolean;
  floor: "" | "ground" | "middle" | "top";
  /** "excellent" is the one condition Idealista cannot express (stato=6). */
  condition: "" | "new" | "good" | "excellent" | "to_renovate";
}

export type ViewMode = "grid" | "map";
