"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-07-11 15:20:33.925666
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('floor', sa.String(), nullable=False),
    sa.Column('sqm', sa.Float(), nullable=True),
    sa.Column('contract', sa.String(), nullable=False),
    sa.Column('current_min_price', sa.Float(), nullable=True),
    sa.Column('first_price', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('filtered_reason', sa.String(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('gone_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_contract'), ['contract'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_fingerprint'), ['fingerprint'], unique=False)

    op.create_table('search_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('portal', sa.String(), nullable=False),
    sa.Column('search_url', sa.String(), nullable=False),
    sa.Column('excluded_keywords', sa.Text(), nullable=False),
    sa.Column('notify_channels', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(), nullable=False),
    sa.Column('last_run_detail', sa.String(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('baseline_done', sa.Boolean(), nullable=False),
    sa.Column('health_alert_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal', sa.String(), nullable=False),
    sa.Column('portal_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('sqm', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False, server_default=""),
    sa.Column('contract', sa.String(), nullable=False),
    sa.Column('email_from', sa.String(), nullable=False),
    sa.Column('email_subject', sa.String(), nullable=False),
    sa.Column('email_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imported_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imported_listings_portal'), ['portal'], unique=False)
        batch_op.create_index(batch_op.f('ix_imported_listings_portal_id'), ['portal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_imported_listings_status'), ['status'], unique=False)

    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('portal', sa.String(), nullable=False),
    sa.Column('portal_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('agency', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_portal'), ['portal'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_portal_id'), ['portal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_property_id'), ['property_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_property_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_property_id'))
        batch_op.drop_index(batch_op.f('ix_listings_portal_id'))
        batch_op.drop_index(batch_op.f('ix_listings_portal'))

    op.drop_table('listings')
    with op.batch_alter_table('imported_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imported_listings_status'))
        batch_op.drop_index(batch_op.f('ix_imported_listings_portal_id'))
        batch_op.drop_index(batch_op.f('ix_imported_listings_portal'))

    op.drop_table('imported_listings')
    op.drop_table('search_profiles')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_properties_contract'))
        batch_op.drop_index(batch_op.f('ix_properties_city'))

    op.drop_table('properties')
    # ### end Alembic commands ###
