/**
 * Measure the bundle, so "the dashboard is heavy" can be checked instead of felt.
 *
 * `docs/audit.md` §7 is the procedure; this is its instrument for the frontend,
 * the way `measure_backend.py` is its instrument for the API. It asserts
 * nothing — it prints numbers, and the ones recorded in §7 are what a later run
 * is compared against.
 *
 * `vite build` already prints the size of each chunk, which answers "how big"
 * and nothing else. The question §7 asks is "big with what, and who pays for
 * it": the app ships one JavaScript chunk with no route-level splitting, so
 * every route pays for every other route's dependencies, and the only way to
 * see that is to attribute the built bytes back to the sources they came from.
 *
 * So this builds once with sourcemaps into a temporary directory — never over
 * `frontend/dist`, which is what the packaged app serves — walks the mappings,
 * and charges each span of generated code to the file it came from. The result
 * accounts for ~99% of the chunk; what is left is the runtime glue that belongs
 * to no source.
 *
 * Run it from the repository root, with the frontend's dependencies installed:
 *
 *     node scripts/measure_frontend.mjs
 *
 * It needs no network, no backend and no browser.
 */

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, readdirSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const FRONTEND = join(ROOT, "frontend");

const B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/** One VLQ-encoded segment of a sourcemap line, as its signed integer fields. */
function decodeSegment(segment) {
  const fields = [];
  let shift = 0;
  let value = 0;
  for (const character of segment) {
    const digit = B64.indexOf(character);
    value += (digit & 31) << shift;
    if (digit & 32) {
      shift += 5;
      continue;
    }
    const negative = value & 1;
    value >>= 1;
    fields.push(negative ? -value : value);
    value = 0;
    shift = 0;
  }
  return fields;
}

/**
 * Generated bytes per source file.
 *
 * A mapping marks where a source's output begins, not how long it is, so each
 * one owns the code up to the next mapping. Segments are sorted by absolute
 * offset first: minified output is a handful of very long lines, and the
 * mappings within one are already in order, but the run of bytes a mapping owns
 * can cross a line ending.
 */
function bytesPerSource(code, map) {
  const lineStarts = [];
  let offset = 0;
  for (const line of code.split("\n")) {
    lineStarts.push(offset);
    offset += line.length + 1;
  }

  const marks = [];
  let sourceIndex = 0;
  map.mappings.split(";").forEach((line, lineNumber) => {
    let column = 0;
    if (!line) return;
    for (const segment of line.split(",")) {
      const fields = decodeSegment(segment);
      if (!fields.length) continue;
      column += fields[0];
      if (fields.length >= 4) sourceIndex += fields[1];
      marks.push([lineStarts[lineNumber] + column, fields.length >= 4 ? sourceIndex : -1]);
    }
  });
  marks.sort((a, b) => a[0] - b[0]);

  const bytes = new Map();
  for (let i = 0; i < marks.length; i++) {
    const [start, source] = marks[i];
    if (source < 0) continue;
    const end = i + 1 < marks.length ? marks[i + 1][0] : code.length;
    bytes.set(source, (bytes.get(source) ?? 0) + Math.max(0, end - start));
  }
  return bytes;
}

/** A source path, as the thing a reader would decide to stop shipping. */
function bucket(source) {
  const dependency = source.match(/node_modules\/((?:@[^/]+\/)?[^/]+)/);
  if (dependency) return `dep: ${dependency[1]}`;
  const locale = source.match(/\/src\/i18n\/(en|it)\.ts/);
  if (locale) return `app: i18n/${locale[1]} (one locale)`;
  const area = source.match(/\/src\/([^/]+)\//);
  if (area) return `app: src/${area[1]}`;
  return `app: ${source.split("/src/")[1] ?? source}`;
}

function kb(bytes) {
  return `${String(Math.round(bytes / 1024)).padStart(5)} kB`;
}

const outDir = mkdtempSync(join(tmpdir(), "bundle-measure-"));
try {
  console.log(`frontend measurement — ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC`);
  console.log("\nbuilding with sourcemaps (not into frontend/dist)...");
  // vite's entry script under this node, rather than `npx` under a shell: the
  // launcher on Windows is a `.cmd`, which needs a shell to resolve, and that
  // shell would interpolate a temporary path nobody chose into a command line.
  const vite = join(FRONTEND, "node_modules", "vite", "bin", "vite.js");
  execFileSync(process.execPath, [vite, "build", "--sourcemap", "--outDir", outDir, "--emptyOutDir"], {
    cwd: FRONTEND,
    stdio: ["ignore", "ignore", "inherit"],
  });

  const assets = join(outDir, "assets");
  const files = readdirSync(assets);
  const scripts = files.filter((name) => name.endsWith(".js"));
  const styles = files.filter((name) => name.endsWith(".css"));

  console.log("\n== what is shipped ==");
  for (const name of [...scripts, ...styles]) {
    console.log(`  ${kb(statSync(join(assets, name)).size)}  ${name}`);
  }
  console.log(
    `  ${scripts.length} script chunk${scripts.length === 1 ? "" : "s"}: ` +
      `${scripts.length === 1 ? "no route-level splitting — every route pays for every other" : "split"}`,
  );

  const totals = new Map();
  let bundleBytes = 0;
  let attributed = 0;
  for (const name of scripts) {
    const code = readFileSync(join(assets, name), "utf8");
    bundleBytes += code.length;
    const map = JSON.parse(readFileSync(join(assets, `${name}.map`), "utf8"));
    for (const [index, size] of bytesPerSource(code, map)) {
      const key = bucket(map.sources[index] ?? "?");
      totals.set(key, (totals.get(key) ?? 0) + size);
      attributed += size;
    }
  }

  const ranked = [...totals].sort((a, b) => b[1] - a[1]);
  const share = ((attributed / bundleBytes) * 100).toFixed(1);
  console.log(`\n== where the JavaScript comes from ==  ${share}% of it attributed`);
  for (const [name, size] of ranked.slice(0, 15)) {
    console.log(`  ${kb(size)}  ${((size / bundleBytes) * 100).toFixed(1).padStart(5)}%  ${name}`);
  }
} finally {
  rmSync(outDir, { recursive: true, force: true });
}
